#!/bin/sh

# Copyright 2017 Jakub Kukiełka

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

OPTIND=1

export FLASK_DEBUG=0
export FLASK_APP="app.py"

while getopts "da:" opt; do
    case "$opt" in
        d)
            # do stuff
            export FLASK_DEBUG=1
            ;;
        a)
            # do stuff
            export FLASK_APP="$OPTARG"
            ;;
        \?)
            echo "Invalid option -$OPTARG" >&2
            ;;
        :)
            echo "Option -$OPTARG requires an argument" >&2
    esac
done

shift $((OPTIND-1))

if [ "$1" == "run" ]; then
    echo -e "\033[0;31mWarning: This server is for development only and not for deployment use!\033[0m"
fi

flask "$1"
