#!/bin/sh

OPTIND=1

export FLASK_DEBUG=0
export FLASK_APP="app.py"

while getopts "da:" opt; do
    case "$opt" in
        d)
            # do stuff
            export FLASK_DEBUG=1
            ;;
        a)
            # do stuff
            export FLASK_APP="$OPTARG"
            ;;
        \?)
            echo "Invalid option -$OPTARG" >&2
            ;;
        :)
            echo "Option -$OPTARG requires an argument" >&2
    esac
done

shift $((OPTIND-1))

if [ "$1" == "run" ]; then
    echo -e "\033[0;31mWarning: This server is for development only and not for deployment use!\033[0m"
fi

flask "$1"
